In [1]:
import pandas as pd
df= pd.read_csv('human_resource.csv')
df.head()

,id,first_name,last_name,date_of_birth,gender,race,department,job_title,location,hire_date,term_date,location_city,location_state
0,00-0037846,Kimmy,Walczynski,04-06-1991,Male,Hispanic or Latino,Engineering,Programmer Analyst I,Headquarters,20-01-2002,NaN,Cleveland,Ohio
1,00-0041533,Ignatius,Springett,29-06-1984,Male,White,Business Development,Business Analyst,Headquarters,08-04-2019,NaN,Cleveland,Ohio
2,00-0045747,Corbie,Bittlestone,29-07-1989,Male,Black or African American,Sales,Solutions Engineer Manager,Headquarters,12-10-2010,NaN,Cleveland,Ohio
3,00-0055274,Baxy,Matton,14-09-1982,Female,White,Services,Service Tech,Headquarters,10-04-2005,NaN,Cleveland,Ohio
4,00-0076100,Terrell,Suff,11-04-1994,Female,Two or More Races,Product Management,Business Analyst,Remote,29-09-2010,2029-10-29 06:09:38 UTC,Flint,Michigan

In [5]:
df.describe(include = 'all')

,id,first_name,last_name,date_of_birth,gender,race,department,job_title,location,hire_date,term_date,location_city,location_state
count,22214,22214,22214,22214,22214,22214,22214,22214,22214,22214,3929,22214,22214
unique,22214,7758,17754,10854,3,7,13,185,2,7016,3929,77,7
top,00-0037846,Cassie,Ducker,09-05-1972,Male,White,Engineering,Research Assistant II,Headquarters,06-07-2009,2029-10-29 06:09:38 UTC,Cleveland,Ohio
freq,1,12,7,9,11288,6328,6686,754,16715,10,1,16871,18025

In [10]:
df.isnull().sum()

id                    0
first_name            0
last_name             0
date_of_birth         0
gender                0
race                  0
department            0
job_title             0
location              0
hire_date             0
term_date         18285
location_city         0
location_state        0
dtype: int64

In [13]:
df['term_date'] = pd.to_datetime(df['term_date'])
df['term_date'] = df.groupby('department')['term_date'].transform(lambda x: x.fillna(x.median()))

In [14]:
df.isnull().sum()

id                0
first_name        0
last_name         0
date_of_birth     0
gender            0
race              0
department        0
job_title         0
location          0
hire_date         0
term_date         0
location_city     0
location_state    0
dtype: int64

In [16]:
df.describe()

,id,first_name,last_name,date_of_birth,gender,race,department,job_title,location,hire_date,term_date,location_city,location_state
count,22214,22214,22214,22214,22214,22214,22214,22214,22214,22214,22214,22214,22214
unique,22214,7758,17754,10854,3,7,13,185,2,7016,NaN,77,7
top,00-0037846,Cassie,Ducker,09-05-1972,Male,White,Engineering,Research Assistant II,Headquarters,06-07-2009,NaN,Cleveland,Ohio
freq,1,12,7,9,11288,6328,6686,754,16715,10,NaN,16871,18025
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-03-25 17:45:13.383226624+00:00,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-04-15 02:05:19+00:00,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-04-12 19:35:34+00:00,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-02-25 13:34:09+00:00,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-29 22:13:35+00:00,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2041-10-29 03:48:59+00:00,NaN,NaN

In [17]:
df.columns

Index(['id', 'first_name', 'last_name', 'date_of_birth', 'gender', 'race',
       'department', 'job_title', 'location', 'hire_date', 'term_date',
       'location_city', 'location_state'],
      dtype='object')

In [19]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine


username = "postgres"
password = "@Skataria123"
host = "localhost"
port = "5432"
database = "hr_dashboard"

encoded_password = quote_plus(password)
engine = create_engine(f"postgresql+psycopg2://{username}:{encoded_password}@{host}:{port}/{database}")

table_name = "dashboard"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' , '{database}'." )

Data successfully loaded into table 'dashboard' , 'hr_dashboard'.